FROM node:18

ENV NP_SESSION_TRACKER_HOME=/np-session-tracker
ENV NP_SESSION_TRACKER_PORT=34418

ARG ROOT_DIR=/app

RUN mkdir  $ROOT_DIR
RUN mkdir  $NP_SESSION_TRACKER_HOME
ADD . $ROOT_DIR/

WORKDIR $ROOT_DIR

RUN npm install
RUN npm run build

WORKDIR $ROOT_DIR/lib

ENTRYPOINT ["node", "index.js"]

VOLUME $NP_SESSION_TRACKER_HOME/log
EXPOSE $NP_SESSION_TRACKER_PORT/tcp
